# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=600"]
  else
    config.vm.synced_folder ".", "/vagrant"
  end
  (1..2).each do |i|
    config.vm.define "node#{i}" do |d|
      d.vm.box = "bento/centos-7.6"
      d.vm.hostname = "node#{i}"
      d.vm.network "private_network", ip: "100.100.100.10#{i}" 
      d.vm.provision "shell", inline: <<-SHELL
        sudo   rpm -Uvh https://yum.postgresql.org/11/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        sudo   yum install  -y  postgresql11-server
        #sudo yum -y install yum-utils  openssl-devel bzip2-devel libffi-devel rsync
        #sudo yum -y groupinstall development
        #sudo yum -y install https://centos7.iuscommunity.org/ius-release.rpm
        #sudo yum -y install  python36u
        #sudo yum -y install  python36u-pip python36u-devel
        #sudo pip3.6 install --upgrade pip
        #sudo pip3.6 install  argcomplete  argh      python-dateutil   setuptools  
        #sudo yum -y install  barman
      SHELL
      d.vm.provision :shell, path: "scripts/post-deploy.sh"
      d.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 1
      end 
    end
  end
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
    config.vbguest.no_install = true
    config.vbguest.no_remote = true
  end
end 